services:

  amo: # container 1 - e suas informações
    image: postgres
    container_name: AMOTUR_DB # podemos escolher qualquer nome
    environment: # variaveis do arquivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
     - "5433:5432" #o primeiro se refere a dentro do container e o segundo a que esta fora.